version: "3"

services:
  postgres_bambino:
    image: "postgres:latest"
    ports:
      - "5430:5432"
    env_file:
      - ".env-dev"
    volumes:
      - ~/postgres_bambino_volume/:/var/lib/postgresql/data/
volumes:
  bambino_db: